Remove-Printer -Name "Microsoft XPS Document Writer"
Remove-Printer -Name "OneNote for Windows 10"
Remove-Printer -Name "OneNote (Desktop)"
Remove-Printer -Name "OneNote"
Remove-Printer -Name "Fax"
Remove-Printer -Name "Fax - HP ColorLaserJet MFP M278-M281"
Remove-Printer -Name "Brother PC-FAX v.3.2"
Remove-Printer -Name "Send To OneNote 2013"
Remove-Printer -Name "AnyDesk Printer"