Get-AppxPackage -AllUsers Microsoft.BingWeather | Remove-AppxPackage                  
Get-AppxPackage -AllUsers Microsoft.BingNews | Remove-AppxPackage                     
Get-AppxPackage -AllUsers *messaging* | Remove-AppxPackage                           
Get-AppxPackage -AllUsers Microsoft.WindowsMaps | Remove-AppxPackage                   
Get-AppxPackage -AllUsers *Skype* | Remove-AppxPackage                                 
Get-AppxPackage -AllUsers Microsoft.MicrosoftOfficeHub | Remove-AppxPackage           
Get-AppxPackage -AllUsers *ACG* | Remove-AppxPackage                                  
Get-AppxPackage -AllUsers *CandyCrush* | Remove-AppxPackage                             
Get-AppxPackage -AllUsers *Facebook* | Remove-AppxPackage                               
Get-AppxPackage -AllUsers *Plex* | Remove-AppxPackage                                  
Get-AppxPackage -AllUsers *Spotify* | Remove-AppxPackage                                
Get-AppxPackage -AllUsers *Twitter* | Remove-AppxPackage                                
Get-AppxPackage -AllUsers *Viber* | Remove-AppxPackage                                 
Get-AppxPackage -AllUsers *TikTok* | Remove-AppxPackage                                  
Get-AppxPackage -AllUsers *Instagram* | Remove-AppxPackage                                
Get-AppxPackage -AllUsers *Messenger* | Remove-AppxPackage                              
Get-AppxPackage -AllUsers *Prime.Video* | Remove-AppxPackage                                 